name: Stryker.NET mutation testing

on: [push, pull_request]

jobs:
  stryker_net:
    runs-on: ubuntu-latest
    # permissions.pull-request:write is required to send a report message to a pull request (when send-report-message: "true")
    permissions:
      pull-requests: write
    name: Stryker.NET GitHub action
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Stryker.NET
        uses: kurnakovv/stryker-net-action@v1.0.0
        with:
          config-path: ".config/stryker-config.json"
          dashboard-api-key: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
